-- begin TIMETABLEFORSTUDENTS_LESSON
alter table TIMETABLEFORSTUDENTS_LESSON add constraint FK_TIMETABLEFORSTUDENTS_LESSON_ON_TEACHER foreign key (TEACHER_ID) references TIMETABLEFORSTUDENTS_TEACHER(ID)^
create index IDX_TIMETABLEFORSTUDENTS_LESSON_ON_TEACHER on TIMETABLEFORSTUDENTS_LESSON (TEACHER_ID)^
-- end TIMETABLEFORSTUDENTS_LESSON
-- begin TIMETABLEFORSTUDENTS_TEACHER
create unique index IDX_TIMETABLEFORSTUDENTS_TEACHER_UNIQ_EMAIL on TIMETABLEFORSTUDENTS_TEACHER (EMAIL)^
create index IDX_TIMETABLEFORSTUDENTS_TEACHER_FIRST_NAME on TIMETABLEFORSTUDENTS_TEACHER (FIRST_NAME)^
-- end TIMETABLEFORSTUDENTS_TEACHER
